"""Reports Celery Tasks"""
import logging
from celery import shared_task

logger = logging.getLogger(__name__)


@shared_task(bind=True, max_retries=2)
def generate_report_task(self, report_id: str):
    """Generate PDF report for a dataset"""
    from .models import Report
    from apps.datasets.models import Dataset
    from apps.analysis.models import DataProfile, Visualization
    from apps.insights.models import DatasetInsight
    import io
    from django.core.files.base import ContentFile
    
    try:
        report = Report.objects.get(id=report_id)
        report.status = 'generating'
        report.save(update_fields=['status'])
        
        dataset = report.dataset
        
        # Try to generate PDF with reportlab
        try:
            pdf_content = _generate_pdf(report, dataset)
            filename = f"report_{report_id[:8]}.pdf"
            report.file.save(filename, ContentFile(pdf_content))
            report.status = 'ready'
        except ImportError:
            # Fallback: generate HTML report
            html_content = _generate_html_report(report, dataset)
            filename = f"report_{report_id[:8]}.html"
            report.file.save(filename, ContentFile(html_content.encode('utf-8')))
            report.status = 'ready'
        
        report.save(update_fields=['status', 'file'])
        logger.info(f"Report {report_id} generated successfully")
        
    except Exception as e:
        logger.error(f"Failed to generate report {report_id}: {e}", exc_info=True)
        try:
            report = Report.objects.get(id=report_id)
            report.status = 'failed'
            report.save(update_fields=['status'])
        except:
            pass
        raise self.retry(exc=e)


def _generate_html_report(report, dataset):
    """Generate HTML report as fallback"""
    from apps.analysis.models import DataProfile
    from apps.insights.models import DatasetInsight
    
    try:
        profile = DataProfile.objects.get(dataset=dataset)
    except:
        profile = None
    
    insights = DatasetInsight.objects.filter(dataset=dataset, is_dismissed=False)[:10]
    
    rows = profile.total_rows if profile else dataset.row_count or 0
    cols = profile.total_columns if profile else dataset.column_count or 0
    quality = profile.data_quality_score if profile else 0
    missing = profile.missing_percentage if profile else 0
    dups = profile.duplicate_percentage if profile else 0
    
    insight_html = ""
    for ins in insights:
        color = {'info': '#00d4ff', 'warning': '#f59e0b', 'critical': '#ef4444', 'success': '#10b981'}.get(ins.severity, '#666')
        insight_html += f'<div style="border-left: 3px solid {color}; padding: 10px 15px; margin: 8px 0; background: rgba(255,255,255,0.03);"><strong>{ins.title}</strong><p style="margin:4px 0; color: #a0aec0; font-size:13px;">{ins.content}</p></div>'
    
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>DataIQ Report: {dataset.name}</title>
<style>
  body {{ font-family: 'IBM Plex Mono', monospace; background: #0f0f19; color: #e2e8f0; padding: 40px; }}
  h1 {{ color: #00d4ff; border-bottom: 1px solid #1e293b; padding-bottom: 10px; }}
  h2 {{ color: #7c3aed; margin-top: 30px; }}
  .metric {{ display: inline-block; background: #1a1a2e; border: 1px solid #1e293b; border-radius: 8px; padding: 15px 25px; margin: 8px; text-align: center; }}
  .metric-value {{ font-size: 28px; color: #00d4ff; font-weight: bold; }}
  .metric-label {{ font-size: 12px; color: #718096; }}
</style>
</head>
<body>
<h1>📊 DataIQ Analysis Report</h1>
<p style="color:#718096">Dataset: {dataset.name} | Generated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M UTC')}</p>

<h2>Overview</h2>
<div>
  <div class="metric"><div class="metric-value">{rows:,}</div><div class="metric-label">Total Rows</div></div>
  <div class="metric"><div class="metric-value">{cols}</div><div class="metric-label">Columns</div></div>
  <div class="metric"><div class="metric-value">{quality:.0f}/100</div><div class="metric-label">Quality Score</div></div>
  <div class="metric"><div class="metric-value">{missing:.1f}%</div><div class="metric-label">Missing Data</div></div>
  <div class="metric"><div class="metric-value">{dups:.1f}%</div><div class="metric-label">Duplicates</div></div>
</div>

<h2>AI Insights</h2>
{insight_html or '<p style="color:#718096">No insights available.</p>'}

<hr style="border-color:#1e293b; margin: 30px 0">
<p style="color:#4a5568; font-size:12px">Generated by DataIQ Platform • Intelligence-Driven Data Analysis</p>
</body>
</html>"""


def _generate_pdf(report, dataset):
    """Generate PDF using reportlab"""
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    import io
    
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    
    # Title
    story.append(Paragraph(f"DataIQ Report: {dataset.name}", styles['Title']))
    story.append(Spacer(1, 12))
    story.append(Paragraph(f"Rows: {dataset.row_count} | Columns: {dataset.column_count}", styles['Normal']))
    
    doc.build(story)
    return buffer.getvalue()
